sudo: requierd
services:
        - docker
before_install:
 - docker build -t vor5tim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vor5tim/react-test npm run test

after_success:
   - docker build -t vor5tim/multi-client ./client
   - docker build -t vor5tim/multi-nginx ./nginx
   - docker build -t vor5tim/multi-server ./server
   - docker build -t vor5tim/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push vor5tim/multi-client
   - docker push vor5tim/multi-nginx
   - docker push vor5tim/multi-server
   - docker push vor5tim/multi-worker  


